# Generated by Django 4.1.3 on 2022-11-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cartoons.commonfields')),
                ('photo', models.ImageField(blank=True, upload_to='actors/')),
            ],
            bases=('Cartoons.commonfields',),
        ),
        migrations.CreateModel(
            name='CartoonCategory',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cartoons.commonfields')),
            ],
            bases=('Cartoons.commonfields',),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cartoons.commonfields')),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('season_number', models.PositiveSmallIntegerField()),
                ('episode_url', models.URLField()),
            ],
            bases=('Cartoons.commonfields',),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cartoons.commonfields')),
                ('image', models.ImageField(upload_to='screenshots/')),
            ],
            bases=('Cartoons.commonfields',),
        ),
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Cartoons.commonfields')),
                ('tagline', models.CharField(max_length=100, verbose_name='слоган мультика')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год выпуска')),
                ('number_of_episodes', models.PositiveSmallIntegerField(verbose_name='количество серий')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('country', models.CharField(max_length=50, verbose_name='Страна производитель')),
                ('actors', models.ManyToManyField(to='Cartoons.actor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartoons.cartooncategory')),
                ('episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartoons.episode')),
                ('screenshots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cartoons.screenshot')),
            ],
            bases=('Cartoons.commonfields',),
        ),
    ]
